CREATE TABLE IF NOT EXISTS teams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    wins INT NOT NULL DEFAULT 0,
    losses INT NOT NULL DEFAULT 0,
    win_pct DOUBLE NOT NULL DEFAULT 0.0,
    games_behind DOUBLE NOT NULL DEFAULT 0.0,
    games_played INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team_id INT NULL,
    Singles INT NOT NULL DEFAULT 0,
    Doubles INT NOT NULL DEFAULT 0,
    Triples INT NOT NULL DEFAULT 0,
    Dimes INT NOT NULL DEFAULT 0,
    HRs INT NOT NULL DEFAULT 0,
    Avg DOUBLE NOT NULL DEFAULT 0.0,
    GP INT NOT NULL DEFAULT 0,
    AtBats INT NOT NULL DEFAULT 0,
    hits INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES teams(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;